### ISSUE TITLE
Erreur date limite de paiement facture

### ISSUE THREAD

**Issue by dlalleme** [maximejay/dolibarr_alpiroc#2]
Bonjour,

Le libellé de date de limite de paiement est incorrect dans le fichier alpiroc/core/modules/facture/doc/pdf_alpiroc_fact.modules.php ligne 2121

Ce devrait être
`$pdf->MultiCell(100, 3, $outputlangs->transnoentities("DateDue")." : " . dol_print_date($object->date_lim_reglement,"day",false,$outputlangs,true), '', 'R');`
au lieu de
`$pdf->MultiCell(100, 3, $outputlangs->transnoentities("DateEndPropal")." : " . dol_print_date($object->fin_validite,"day",false,$outputlangs,true), '', 'R');`

Cordialement

**Comment by maximejay** [comment]
Merci,
Cela doit être corrigé dans la version V1.2.9
