### ISSUE TITLE
Problème note_publique wisiwig

### ISSUE THREAD

**Issue by dlalleme** [maximejay/dolibarr_alpiroc#3]
Bonjour,
La note publique saisie à l'aide de l'éditeur HTML ne s'affiche pas correctement dans le document pdf généré.
Il faut donc remplacer la fonction **MultiCell** par la fonction **writeHTMLCell** aux lignes suivantes : 

- 2269 fichier pdf_alpiroc.modules.php
- 2255 fichier pdf_alpiroc_fact.modules.php
- 2269 fichier pdf_alpiroc_con.modules.php

Cordialement
Denis

**Comment by maximejay** [comment]
Merci !
Normalement corrigé dans la release 1.2.10
Cordialement
