### ISSUE TITLE
Mise à jour pour les versions 5 et 6

### ISSUE THREAD

**Issue by yannkraw** [maximejay/dolibarr_alpiroc#5]
Bonjour Maxime,
Est ce que le développement continue sur ce module pour une compatibilité avec les versions 5 et surtout 6 de Dolibarr ?

Bien à toi

**Comment by tiramiseb** [comment]
Bonjour Yann,

J'ai effectué quelques modifications pour que ça fonctionne avec Dolibarr 6.0.4, cf https://github.com/maximejay/dolibarr_alpiroc/pull/4. Pas de réponse de Maxime.

**Comment by maximejay** [comment]
Bonjour,
Merci pour votre contribution, je vais tenter de merger cette pull request. Cela serait bien que le développement continue. Je n'ai pas beaucoup de temps à consacrer au module et je ne suis pas utilisateur de Dolibarr, j'ai donc un peu de mal à suivre les nouvelles versions. Si vous utilisez le module et que vous souhaitez poursuivre son développement c'est avec plaisir ! 
Maxime

**Comment by tiramiseb** [comment]
Je ne peux pas m'engager à reprendre le projet, j'ai juste adapté le code pour que ça fonctionne. Je n'hésiterai pas à refaire une PR si je fais des améliorations.

**Comment by yannkraw** [comment]
Merci pour les réponses et les modifications, je pense également contribué à l'amélioration du module en fonction de mes demandes clients.
Je ferais des PR le cas échéant.
